//
//  Symbols.swift
//  SwiftUIDemo
//
//  Created by Marshal on 2022/1/19.
//

import UIKit

public var Symbols: [String] = """
square.and.arrow.up
square.and.arrow.up.fill
square.and.arrow.down
square.and.arrow.down.fill
square.and.arrow.up.on.square
square.and.arrow.up.on.square.fill
square.and.arrow.down.on.square
square.and.arrow.down.on.square.fill
pencil
pencil.circle
pencil.circle.fill
pencil.slash
square.and.pencil
scribble
pencil.and.outline
pencil.tip
pencil.tip.crop.circle
pencil.tip.crop.circle.badge.plus
pencil.tip.crop.circle.badge.minus
lasso
trash
trash.fill
trash.circle
trash.circle.fill
trash.slash
trash.slash.fill
folder
folder.fill
folder.circle
folder.circle.fill
folder.badge.plus
folder.fill.badge.plus
folder.badge.minus
folder.fill.badge.minus
folder.badge.person.crop
folder.fill.badge.person.crop
paperplane
paperplane.fill
tray
tray.fill
tray.and.arrow.up
tray.and.arrow.up.fill
tray.and.arrow.down
tray.and.arrow.down.fill
tray.2
tray.2.fill
tray.full
tray.full.fill
archivebox
archivebox.fill
arrow.up.bin
arrow.up.bin.fill
doc
doc.fill
doc.circle
doc.circle.fill
arrow.up.doc
arrow.up.doc.fill
arrow.down.doc
arrow.down.doc.fill
doc.text
doc.text.fill
doc.on.doc
doc.on.doc.fill
doc.on.clipboard
doc.on.clipboard.fill
doc.richtext
doc.plaintext
doc.append
doc.text.magnifyingglass
calendar
calendar.circle
calendar.circle.fill
calendar.badge.plus
calendar.badge.minus
arrowshape.turn.up.left
arrowshape.turn.up.left.fill
arrowshape.turn.up.left.circle
arrowshape.turn.up.left.circle.fill
arrowshape.turn.up.right
arrowshape.turn.up.right.fill
arrowshape.turn.up.right.circle
arrowshape.turn.up.right.circle.fill
arrowshape.turn.up.left.2
arrowshape.turn.up.left.2.fill
book
book.fill
book.circle
book.circle.fill
bookmark
bookmark.fill
rosette
paperclip
paperclip.circle
paperclip.circle.fill
rectangle.and.paperclip
link
link.circle
link.circle.fill
personalhotspot
person
person.fill
person.circle
person.circle.fill
person.badge.plus
person.badge.minus
person.2
person.2.fill
person.3
person.3.fill
person.crop.circle
person.crop.circle.fill
person.crop.circle.badge.plus
person.crop.circle.fill.badge.plus
person.crop.circle.badge.minus
person.crop.circle.fill.badge.minus
person.crop.circle.badge.checkmark
person.crop.circle.fill.badge.checkmark
person.crop.circle.badge.xmark
person.crop.circle.fill.badge.xmark
person.crop.square
person.crop.square.fill
person.crop.rectangle
person.crop.rectangle.fill
command
option
alt
clear
clear.fill
delete.left
delete.left.fill
delete.right
delete.right.fill
shift
shift.fill
capslock
capslock.fill
escape
power
globe
sun.min
sun.min.fill
sun.max
sun.max.fill
sunrise
sunrise.fill
sunset
sunset.fill
sun.dust
sun.dust.fill
sun.haze
sun.haze.fill
moon
moon.fill
moon.circle
moon.circle.fill
zzz
moon.zzz
moon.zzz.fill
sparkles
moon.stars
moon.stars.fill
cloud
cloud.fill
cloud.drizzle
cloud.drizzle.fill
cloud.rain
cloud.rain.fill
cloud.heavyrain
cloud.heavyrain.fill
cloud.fog
cloud.fog.fill
cloud.hail
cloud.hail.fill
cloud.snow
cloud.snow.fill
cloud.sleet
cloud.sleet.fill
cloud.bolt
cloud.bolt.fill
cloud.bolt.rain
cloud.bolt.rain.fill
cloud.sun
cloud.sun.fill
cloud.sun.rain
cloud.sun.rain.fill
cloud.sun.bolt
cloud.sun.bolt.fill
cloud.moon
cloud.moon.fill
cloud.moon.rain
cloud.moon.rain.fill
cloud.moon.bolt
cloud.moon.bolt.fill
smoke
smoke.fill
wind
wind.snow
tornado
tropicalstorm
hurricane
thermometer.sun
thermometer.snowflake
thermometer
umbrella
umbrella.fill
flame
flame.fill
light.min
light.max
rays
slowmo
timelapse
keyboard
keyboard.chevron.compact.down
square.grid.3x2
square.grid.3x2.fill
rectangle.grid.3x2
rectangle.grid.3x2.fill
square.grid.2x2
square.grid.2x2.fill
rectangle.grid.2x2
rectangle.grid.2x2.fill
square.grid.4x3.fill
rectangle.grid.1x2
rectangle.grid.1x2.fill
circle.grid.2x2
circle.grid.2x2.fill
circle.grid.3x3
circle.grid.3x3.fill
checkmark.seal
checkmark.seal.fill
xmark.seal
xmark.seal.fill
exclamationmark.triangle
exclamationmark.triangle.fill
drop.triangle
drop.triangle.fill
play
play.fill
play.circle
play.circle.fill
play.rectangle
play.rectangle.fill
pause
pause.fill
pause.circle
pause.circle.fill
pause.rectangle
pause.rectangle.fill
stop
stop.fill
stop.circle
stop.circle.fill
playpause
playpause.fill
backward
backward.fill
forward
forward.fill
backward.end
backward.end.fill
forward.end
forward.end.fill
backward.end.alt
backward.end.alt.fill
forward.end.alt
forward.end.alt.fill
eject
eject.fill
memories
memories.badge.plus
memories.badge.minus
shuffle
repeat
repeat.1
speaker
speaker.fill
speaker.slash
speaker.slash.fill
speaker.zzz
speaker.zzz.fill
badge.plus.radiowaves.right
music.note
music.note.list
music.mic
goforward
gobackward
goforward.10
gobackward.10
goforward.15
gobackward.15
goforward.30
gobackward.30
goforward.45
gobackward.45
goforward.60
gobackward.60
goforward.75
gobackward.75
goforward.90
gobackward.90
goforward.plus
gobackward.minus
magnifyingglass
magnifyingglass.circle
magnifyingglass.circle.fill
plus.magnifyingglass
minus.magnifyingglass
1.magnifyingglass
mic
mic.fill
mic.circle
mic.circle.fill
mic.slash
mic.slash.fill
circle
circle.fill
smallcircle.circle
smallcircle.circle.fill
capsule
capsule.fill
square
square.fill
square.split.2x1
square.split.2x1.fill
square.split.1x2
square.split.1x2.fill
square.split.2x2
square.split.2x2.fill
dot.square
dot.square.fill
square.on.square
square.fill.on.square.fill
plus.square.on.square
plus.square.fill.on.square.fill
square.on.circle
square.fill.on.circle.fill
square.stack
square.stack.fill
app
app.fill
rectangle
rectangle.fill
rectangle.split.3x1
rectangle.split.3x1.fill
rectangle.split.3x3
rectangle.on.rectangle
rectangle.fill.on.rectangle.fill
plus.rectangle.on.rectangle
plus.rectangle.fill.on.rectangle.fill
triangle
triangle.fill
hexagon
hexagon.fill
suit.heart
suit.heart.fill
suit.club
suit.club.fill
suit.spade
suit.spade.fill
suit.diamond
suit.diamond.fill
heart
heart.fill
heart.circle
heart.circle.fill
heart.slash
heart.slash.fill
heart.slash.circle
heart.slash.circle.fill
rhombus
rhombus.fill
star
star.fill
star.circle
star.circle.fill
star.slash
star.slash.fill
flag
flag.fill
flag.circle
flag.circle.fill
flag.slash
flag.slash.fill
location
location.fill
location.circle
location.circle.fill
location.slash
location.slash.fill
location.north
location.north.fill
location.north.line
location.north.line.fill
bell
bell.fill
bell.circle
bell.circle.fill
bell.slash
bell.slash.fill
tag
tag.fill
tag.circle
tag.circle.fill
bolt
bolt.fill
bolt.circle
bolt.circle.fill
bolt.slash
bolt.slash.fill
bolt.badge.a
bolt.badge.a.fill
bolt.horizontal
bolt.horizontal.fill
bolt.horizontal.circle
bolt.horizontal.circle.fill
eye
eye.fill
eye.slash
eye.slash.fill
eyeglasses
icloud
icloud.fill
icloud.circle
icloud.circle.fill
icloud.slash
icloud.slash.fill
exclamationmark.icloud
exclamationmark.icloud.fill
xmark.icloud
xmark.icloud.fill
link.icloud
link.icloud.fill
bolt.horizontal.icloud
bolt.horizontal.icloud.fill
person.icloud
person.icloud.fill
lock.icloud
lock.icloud.fill
arrow.clockwise.icloud
arrow.clockwise.icloud.fill
arrow.counterclockwise.icloud
arrow.counterclockwise.icloud.fill
icloud.and.arrow.down
icloud.and.arrow.down.fill
icloud.and.arrow.up
icloud.and.arrow.up.fill
flashlight.off.fill
flashlight.on.fill
camera
camera.fill
camera.circle
camera.circle.fill
camera.on.rectangle
camera.on.rectangle.fill
message
message.fill
message.circle
message.circle.fill
bubble.right
bubble.right.fill
bubble.left
bubble.left.fill
exclamationmark.bubble
exclamationmark.bubble.fill
quote.bubble
quote.bubble.fill
text.bubble
text.bubble.fill
captions.bubble
captions.bubble.fill
plus.bubble
plus.bubble.fill
bubble.middle.bottom
bubble.middle.bottom.fill
bubble.middle.top
bubble.middle.top.fill
bubble.left.and.bubble.right
bubble.left.and.bubble.right.fill
phone
phone.fill
phone.circle
phone.circle.fill
phone.badge.plus
phone.fill.badge.plus
phone.arrow.up.right
phone.fill.arrow.up.right
phone.arrow.down.left
phone.fill.arrow.down.left
phone.arrow.right
phone.fill.arrow.right
phone.down
phone.down.fill
phone.down.circle
phone.down.circle.fill
teletype
teletype.answer
video
video.fill
video.circle
video.circle.fill
video.slash
video.slash.fill
video.badge.plus
arrow.up.right.video
arrow.up.right.video.fill
arrow.down.left.video
arrow.down.left.video.fill
questionmark.video
questionmark.video.fill
envelope
envelope.fill
envelope.circle
envelope.circle.fill
envelope.open
envelope.open.fill
envelope.badge
envelope.badge.fill
gear
signature
scissors
scissors.badge.ellipsis
ellipsis
ellipsis.circle
ellipsis.circle.fill
bag
bag.fill
bag.badge.plus
bag.fill.badge.plus
bag.badge.minus
bag.fill.badge.minus
cart
cart.fill
cart.badge.plus
cart.fill.badge.plus
cart.badge.minus
cart.fill.badge.minus
creditcard
creditcard.fill
wand.and.rays
wand.and.rays.inverse
wand.and.stars
wand.and.stars.inverse
crop
crop.rotate
nosign
gauge
gauge.badge.plus
gauge.badge.minus
speedometer
metronome
tuningfork
paintbrush
paintbrush.fill
bandage
bandage.fill
wrench
wrench.fill
hammer
hammer.fill
eyedropper
eyedropper.halffull
eyedropper.full
printer
printer.fill
briefcase
briefcase.fill
house
house.fill
lock
lock.fill
lock.circle
lock.circle.fill
lock.shield
lock.shield.fill
lock.slash
lock.slash.fill
lock.open
lock.open.fill
lock.rotation
lock.rotation.open
wifi
wifi.slash
wifi.exclamationmark
pin
pin.fill
pin.circle
pin.circle.fill
pin.slash
pin.slash.fill
mappin
mappin.circle
mappin.circle.fill
mappin.slash
mappin.and.ellipse
map
map.fill
safari
safari.fill
rotate.left
rotate.left.fill
rotate.right
rotate.right.fill
selection.pin.in.out
desktopcomputer
headphones
hifispeaker
hifispeaker.fill
tv
tv.fill
tv.circle
tv.circle.fill
airplayvideo
airplayaudio
dot.radiowaves.left.and.right
dot.radiowaves.right
antenna.radiowaves.left.and.right
guitars
airplane
car
car.fill
tram.fill
bed.double
bed.double.fill
hare
hare.fill
tortoise
tortoise.fill
ant
ant.fill
ant.circle
ant.circle.fill
film
film.fill
sportscourt
sportscourt.fill
qrcode
barcode
viewfinder
viewfinder.circle
viewfinder.circle.fill
barcode.viewfinder
qrcode.viewfinder
camera.viewfinder
faceid
photo
photo.fill
rectangle.badge.checkmark
rectangle.fill.badge.checkmark
rectangle.badge.xmark
rectangle.fill.badge.xmark
photo.on.rectangle
photo.fill.on.rectangle.fill
rectangle.on.rectangle.angled
rectangle.fill.on.rectangle.angled.fill
rectangle.stack
rectangle.stack.fill
rectangle.stack.badge.plus
rectangle.stack.fill.badge.plus
rectangle.stack.badge.minus
rectangle.stack.fill.badge.minus
rectangle.stack.badge.person.crop
sidebar.left
sidebar.right
macwindow
uiwindow.split.2x1
squares.below.rectangle
rectangle.split.3x3.fill
pano
pano.fill
square.and.line.vertical.and.square
flowchart
flowchart.fill
shield
shield.fill
shield.slash
shield.slash.fill
slider.horizontal.3
slider.horizontal.below.rectangle
cube
cube.fill
arkit
square.stack.3d.down.right
square.stack.3d.down.right.fill
square.stack.3d.up
square.stack.3d.up.fill
square.stack.3d.up.slash
square.stack.3d.up.slash.fill
livephoto
livephoto.slash
livephoto.play
scope
helm
clock
clock.fill
alarm
alarm.fill
stopwatch
stopwatch.fill
timer
gamecontroller
gamecontroller.fill
ear
hand.raised
hand.raised.fill
hand.raised.slash
hand.raised.slash.fill
hand.thumbsup
hand.thumbsup.fill
hand.thumbsdown
hand.thumbsdown.fill
hand.draw
hand.draw.fill
hand.point.left
hand.point.left.fill
hand.point.right
hand.point.right.fill
rectangle.compress.vertical
rectangle.expand.vertical
rectangle.and.arrow.up.right.and.arrow.down.left
rectangle.and.arrow.up.right.and.arrow.down.left.slash
chart.bar
chart.bar.fill
chart.pie
chart.pie.fill
burst
burst.fill
waveform.path.ecg
waveform.path
waveform.path.badge.plus
waveform.path.badge.minus
waveform
waveform.circle
waveform.circle.fill
staroflife
staroflife.fill
gift
gift.fill
plus.app
plus.app.fill
app.badge
app.badge.fill
app.gift
app.gift.fill
studentdesk
hourglass
purchased
purchased.circle
purchased.circle.fill
perspective
aspectratio
aspectratio.fill
skew
grid
grid.circle
grid.circle.fill
burn
recordingtape
battery.100
battery.25
battery.0
lightbulb
lightbulb.fill
lightbulb.slash
lightbulb.slash.fill
list.dash
list.bullet
list.bullet.indent
list.number
increase.indent
decrease.indent
decrease.quotelevel
increase.quotelevel
list.bullet.below.rectangle
text.badge.plus
text.badge.minus
text.badge.checkmark
text.badge.xmark
text.badge.star
text.insert
text.append
text.quote
text.alignleft
text.aligncenter
text.alignright
text.justify
textformat.size
textformat
textformat.alt
textformat.superscript
textformat.subscript
textformat.abc
textformat.abc.dottedunderline
bold
italic
underline
strikethrough
bold.italic.underline
""".split(separator: "\n").map({String($0)})
//三个引号可以将字符以这种形式放起来
//使用spilt和map分别将字符分割组合成字符串数组(主要分割出来的是String.SubString类型)
//实际项目推荐一个数组完事

